name: 'Patch Kernel for no-kprobe.'

runs:
  using: 'composite'
  steps:
      - name: Patch Kernel for no-kprobe
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          # Function
          PACK_FILES(){
            temp_dir=$(mktemp -d)
            find . -name "*.rej" -exec cp --parents {} "$temp_dir" \;
            find . -name "*.rej" | sed 's/\.rej$//' | xargs -I {} test -f {} && find . -name "*.rej" | sed 's/\.rej$//' | xargs -I {} cp --parents {} "$temp_dir"
            tar -czf "rej_files_kernel_write_read.tar.gz" -C "$temp_dir" .
            rm -rf "$temp_dir"
            echo "[+] Packed Successfully."

            find . -type f \( -name "*.rej" -o -name "*.orig" \) -delete
            echo "[+] Removed all .rej and .orig files."
            echo "[+] =================================== "
          }
          REJ_FOUND(){
            if [[ "${{ env.BUILD_DEBUGGER }}" == "true" ]]; then
                echo "[+] Checking kernel write and read patch rej files..."
                mapfile -t REJ_FILES < <(find . -type f -name "*.rej")
                if [ ${#REJ_FILES[@]} -eq 0 ]; then
                    echo "[+] Your kernel have no any rej files, Skipped."
                else
                    for CAT_REJ in "${REJ_FILES[@]}"; do
                        echo "[-] Found .rej file: $CAT_REJ"
                        cat $CAT_REJ
                        echo "[+] =================================== "
                    done
                fi

                if [[ "${{ env.SKIP_PATCH }}" == "true" ]]; then
                    echo "[+] SKIP_PATCH enabled, Skipped. "
                    PACK_FILES
                elif [[ "${{ env.SKIP_PATCH }}" != "true" ]]; then
                    echo "[-] Found .rej files, Stopped! "
                    PACK_FILES
                    false
                fi
            fi
          }

          # Detect SuSFS is used to enable the SuSFS inline hook
          if [[ ${{ env.SUSFS_ENABLE }} == "true" ]]; then
            # Core
            cp /tmp/Patches/susfs_inline_hook_patches.sh ./
            bash susfs_inline_hook_patches.sh ./

            echo "[+] executed SuSFS inline hook successfully."

            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
                cp /tmp/Patches/backport_patches.sh ./

                bash backport_patches.sh

                if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                    cp /tmp/Patches/backport_selinux_patches.sh ./

                    bash backport_selinux_patches.sh
                    echo "[+] Patched SELinux."
                else
                    echo "[-] Skipped SELinux Patch."
                fi

                if grep -q "kernel_read" "fs/read_write.c"; then
                    echo ">>>>>>>>>>>>>>>Backport Patch<<<<<<<<<<<<<<<<"
                    echo ">                                           <"
                    echo "Your kernel is already backported, skipping"
                    echo ">                                           <"
                    echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
                elif [[ "${{ env.KERNEL_PATCH }}" == "true" ]]; then
                    if [[ ${{ env.FIRST_VERSION }} -lt 4 ]] && [[ ${{ env.SECOND_VERSION }} -lt 18 ]]; then
                        echo "[-] Could not support ARMV7A kernel(Kernel Version < 3.18)."

                        false
                    elif [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    fi
                    REJ_FOUND
                fi

                echo "[+] executed backport patch (contain kernel_read and kernel_write patch) successfully."
            else
                cp /tmp/Patches/backport_patches.sh ./
                bash backport_patches.sh

                echo "executed backport patch successfully."

                if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                    cp /tmp/Patches/backport_selinux_patches.sh ./

                    bash backport_selinux_patches.sh
                    echo "[+] Patched SELinux."
                else
                    echo "[-] Skipped SELinux Patch."
                fi
            fi

          # Check syscall hook
          elif [[ ${{ env.HOOK_METHOD }} == "syscall" ]]; then
            # Core
            cp /tmp/Patches/syscall_hook_patches.sh ./
            bash syscall_hook_patches.sh ./

            echo "[+] executed syscall hook successfully."

            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
                cp /tmp/Patches/backport_patches.sh ./

                bash backport_patches.sh

                if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                    cp /tmp/Patches/backport_selinux_patches.sh ./

                    bash backport_selinux_patches.sh
                    echo "[+] Patched SELinux."
                else
                    echo "[-] Skipped SELinux Patch."
                fi

                if grep -q "kernel_read" "fs/read_write.c"; then
                    echo ">>>>>>>>>>>>>>>Backport Patch<<<<<<<<<<<<<<<<"
                    echo ">                                           <"
                    echo "Your kernel is already backported, skipping"
                    echo ">                                           <"
                    echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
                elif [[ "${{ env.KERNEL_PATCH }}" == "true" ]]; then
                    if [[ ${{ env.FIRST_VERSION }} -lt 4 ]] && [[ ${{ env.SECOND_VERSION }} -lt 18 ]]; then
                        echo "[-] Could not support ARMV7A kernel(Kernel Version < 3.18)."

                        false
                    elif [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./

                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true

                        echo "[+] Patched kernel_write and kernel_read."
                    fi
                    REJ_FOUND
                fi

                echo "[+] executed backport patch (contain kernel_read and kernel_write patch) successfully."
            else
                cp /tmp/Patches/backport_patches.sh ./
                bash backport_patches.sh

                echo "executed backport patch successfully."

                if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                    cp /tmp/Patches/backport_selinux_patches.sh ./

                    bash backport_selinux_patches.sh
                    echo "[+] Patched SELinux."
                else
                    echo "[-] Skipped SELinux Patch."
                fi
            fi

          else
            echo "[-] please input a vaild option!"
            false

          fi

          # Check for static state in partial functions
          KERNEL_VERSION=$(head -n 3 Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')
          FIRST_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $1}')
          SECOND_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $2}')

          if ! grep -rq "check_symbol_export" "drivers/kernelsu/tools/static_export_check.mk" >/dev/null 2>&1; then
            echo "[-] Your KernelSU needn't this check progress, Skipped."

          elif [[ "${{ env.KPM_ENABLE }}" == "true" ]]; then
            echo "[+] Detected KPM, Skipped."

          elif grep -q "CONFIG_KALLSYMS=y" "./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}" && grep -q "CONFIG_KALLSYMS_ALL=y" "./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}" >/dev/null 2>&1; then
            echo "[+] Detected KALLSYMS enabled, Skipped."

          else
            sed -i 's/^static ssize_t (\*write_op\[\])(struct file \*, char \*, size_t) = {/ssize_t (*write_op[])(struct file *, char *, size_t) = {/' security/selinux/selinuxfs.c
            sed -i 's/^static const struct file_operations sel_handle_status_ops = {/const struct file_operations sel_handle_status_ops = {/' security/selinux/selinuxfs.c

            echo "[+] Removed write_op and sel_handle_status_ops static state."

            if [ "$FIRST_VERSION" -lt 5 ] && [ "$SECOND_VERSION" -lt 15 ]; then
                if grep -q "sel_mutex" "security/selinux/selinuxfs.c" >/dev/null 2>&1; then
                    sed -i 's/^static DEFINE_MUTEX(sel_mutex)/DEFINE_MUTEX(sel_mutex)/' security/selinux/selinuxfs.c
                    echo "[+] Removed sel_mutex static state."

                else
                    echo "[-] Your Kernel haven't sel_mutex, Skipped."
                fi

                if grep -q "selinux_status_page" "security/selinux/ss/status.c" >/dev/null 2>&1; then
                    sed -i 's/^static struct page \*selinux_status_page/struct page *selinux_status_page/' security/selinux/ss/status.c
                    echo "[+] Removed selinux_status_page static state."

                else
                    echo "[-] Your Kernel haven't selinux_status_page, Skipped."
                fi

                if grep -q "selinux_status_lock" "security/selinux/ss/status.c" >/dev/null 2>&1; then
                    sed -i 's/^static DEFINE_MUTEX(selinux_status_lock)/DEFINE_MUTEX(selinux_status_lock)/' security/selinux/ss/status.c
                    echo "[+] Removed selinux_status_lock static state."

                else
                    echo "[-] Your Kernel haven't selinux_status_lock, Skipped."
                fi
            fi

            if [ "$FIRST_VERSION" -lt 4 ] && [ "$SECOND_VERSION" -lt 19 ]; then
                if grep -q "selinux_status_page" "security/selinux/hooks.c" >/dev/null 2>&1; then
                    sed -i 's/^static struct security_operations selinux_ops/struct security_operations selinux_ops/' security/selinux/hooks.c
                    echo "[+] Removed selinux_ops static state."

                else
                    echo "[-] Your Kernel haven't selinux_ops, Skipped."
                fi
            fi

            echo "[+] Checked successfully."
          fi

      - name: Upload Build Kernel Patch Rejected Files
        if: env.BUILD_DEBUGGER == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: patch_kernel_write_read_rejected_files
          path: |
            device_kernel/rej_files_kernel_write_read.tar.gz
