name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:  # <-- This adds the manual "Run workflow" button!
  workflow_call:      # <-- Keeps it callable by other scripts if needed

jobs:
  # Xiaomi Miatoll
  build-miatoll-crdroid12-a16:
    name: "Build Redmi Note 9S/9 Pro (crDroid 12.0 A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-miatoll-crdroid12-a16.yml
    secrets: inherit

 
