name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:  # <-- This adds the manual "Run workflow" button!
  workflow_call:      # <-- Keeps it callable by other scripts if needed

jobs:
  # Xiaomi Miatoll
  build-miatoll-crdroid12-a16:
    name: "Build Redmi Note 9S/9 Pro (crDroid 12.0 A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-miatoll-crdroid12-a16.yml
    secrets: inherit

  # Nothing
  build-nothing-phone-1-lineageos23-a16:
    name: "Nothing Phone (1) (LineageOS 23.0 A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-nothing-phone-1-lineageos23-a16.yml
    secrets: inherit

  build-nothing-phone-1-evox-a16-qpr2:
    name: "Nothing Phone (1) (EvolutionX A16 QPR2)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-nothing-phone-1-evox-a16-qpr2.yml
    secrets: inherit  
  
  # OnePlus
  build-oneplus-nord-ce-3-5g-lineageos23-a16:
    name: "OnePlus Nord CE 3 5G (LineageOS 23 A16 QPR2)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-oneplus-nord-ce-3-5g-lineageos23-a16.yml
    secrets: inherit

  build-oneplus-8-series-oos13-a13-xtd:
    name: "Oneplus 8 Series (ColorOS 13 A13 XTD)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-oneplus-8-series-oos13-a13-xtd.yml
    secrets: inherit
